### ISSUE TITLE
Transferring the npm package to the browserify org

### ISSUE THREAD

**Issue by goto-bus-stop** [browserify/console-browserify#15]
Hi @Raynos! I've merged some PRs here and would like to publish a new version, but the package is still only owned by you on npm. Would you mind granting publish access to the browserify org?

Command line is:
```
npx npm@6.5 access grant read-write browserify:developers console-browserify
```
(newer npm versions have a bug, hence the `npx npm@6.5` stuff)
Thanks!

**Comment by Raynos** [comment]
I could not get the command you asked for working.

Instead I added you as an owner.

```
raynos at raynos-Precision-5530  
~/projects/stripe-stateful-mock on master*
$ npm owner ls console-browserify
npm http fetch GET 200 https://registry.npmjs.org/console-browserify 771ms
goto-bus-stop <renee@kooi.me>
raynos <raynos2@gmail.com>
```

Feel free to run the command yourself.

**Comment by goto-bus-stop** [comment]
perfect, thank you!
